In [18]:
# download from 
# version 4
# https://www.kaggle.com/anttip/wordbatch-1-3-3-fm-ftrl-using-mse-lb-0-9805?scriptVersionId=2738014/output
import pandas as pd
import pickle
df1 = pd.read_csv('../results/lvl0_wordbatch_clean_sub.csv')
df2 = pd.read_csv('../results/lvl0_wordbatch_clean_oof.csv')
df1.head()

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,00001cee341fdb12,0.746235,0.546799,0.717783,0.510125,0.674278,0.544254
1,0000247867823ef7,0.496725,0.498867,0.489681,0.497993,0.497500,0.499389
2,00013b17ad220c46,0.504823,0.498110,0.499367,0.500764,0.495953,0.501030
3,00017563c3f7919a,0.480637,0.494287,0.487092,0.499642,0.486042,0.496019
4,00017695ad8997eb,0.498488,0.495162,0.496843,0.496310,0.499242,0.500360

In [19]:
df2.head()

,id,toxic,severe_toxic,obscene,threat,insult,identity_hate,toxic_oof,severe_toxic_oof,obscene_oof,threat_oof,insult_oof,identity_hate_oof
0,0000997932d777bf,0,0,0,0,0,0,0.475143,0.493181,0.484868,0.496108,0.480469,0.491839
1,000103f0d9cfb60f,0,0,0,0,0,0,0.537743,0.494133,0.502673,0.504284,0.510325,0.494948
2,000113f07ec002fd,0,0,0,0,0,0,0.493843,0.489700,0.494478,0.497599,0.491506,0.494077
3,0001b41b1c6bb37e,0,0,0,0,0,0,0.480992,0.499266,0.494058,0.500773,0.495179,0.502901
4,0001d958c54c6e35,0,0,0,0,0,0,0.520361,0.488580,0.521526,0.490461,0.525445,0.500579

In [20]:
cls = ['toxic','severe_toxic','obscene','threat','insult','identity_hate']
print(df1.columns)
test_pred = df1[cls].values
print(test_pred[:5])

Index(['id', 'toxic', 'severe_toxic', 'obscene', 'threat', 'insult',
       'identity_hate'],
      dtype='object')
[[0.74623459 0.54679934 0.71778266 0.51012543 0.67427809 0.54425436]
 [0.49672536 0.49886678 0.48968069 0.4979933  0.49750006 0.49938892]
 [0.50482256 0.49811017 0.49936666 0.50076415 0.4959531  0.5010298 ]
 [0.4806369  0.49428731 0.48709205 0.49964157 0.48604206 0.4960191 ]
 [0.49848811 0.49516193 0.49684335 0.49630981 0.49924156 0.50036043]]

In [21]:
cls_2 = [x+'_oof' for x in cls]
train_pred = df2[cls_2].values
print(train_pred[:5])

with open('../features/wordbatch_feat.pkl','wb') as fout:
    pickle.dump([train_pred,test_pred],fout)
print('done')

[[0.4751431  0.49318147 0.48486789 0.49610837 0.48046931 0.49183892]
 [0.53774298 0.49413258 0.50267313 0.50428361 0.51032478 0.4949481 ]
 [0.49384291 0.48969967 0.49447785 0.49759911 0.49150614 0.49407677]
 [0.48099214 0.4992659  0.49405792 0.50077326 0.49517931 0.50290114]
 [0.52036095 0.48857999 0.52152574 0.49046141 0.52544549 0.50057891]]
done